title: From Roots To Halo
author: Ascended Woman
email: aw@fromrootstohalo.com
description: Home of the Ascended Woman. Blog for navigating life through the celestial plane.
baseurl: ''
url: 'https://fromrootstohalo.com'
theme: minima
plugins:
  - jekyll-feed
  - jekyll-admin
  - jekyll-toc
  - jekyll-seo-tag
  - jekyll-archives

excerpt_separator: <!--more-->
disqus_shortname: rootstohalo

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


talkyard_server_url: https://comments-for-www-fromrootstohalo-com.talkyard.net
talkyard_script_url: https://c1.ty-cdn.net/-/talkyard-comments.min.js
   