description: All about me and my astrology.
baseurl: ''
url: 'htto://fromrootstohalo.com'
theme: minima
plugins:
  - jekyll-feed
  - jekyll-admin
excerpt_separator: <!--more-->
disqus_shortname: rootstohalo
